[[redirects]]
from = "/#/creative-work/allocate"
to = "/project/allocaterite"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/awake"
to = "/project/awake"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/smart-cities"
to = "/project/smartcities"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/humanifed-branding-web-design-app-development"
to = "/project/humanified"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/ultra-music-animation-design-web-development"
to = "/project/ultra"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/bbc-entertainment-london-calling-design"
to = "/project/london-calling"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/showtime"
to = "/project/ray-donovan"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/base-develops-and-manages"
to = "/project/base"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/coloredge-is-a-unique-media-company"
to = "/project/coloredge"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/city-cancer-challenge"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/rock-summer-is-an-initiative-started"
to = "/project/rock-summer"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/pluto-tv-is-an-Internet-based-television"
to = "/project/pluto-tv"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/oracle-cloud-hero-marketing-design-web-development"
to = "/project/oracle"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/hugo-boss-design-animation"
to = "/project/hugo-boss"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/first-key-homes-strategy-design-web-development"
to = "/project/first-key-homes"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/the-department-design-web-development"
to = "/project/the-department"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/engine-shop-branding-design-web-development"
to = "/project/engineshop"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/bbc-entertainment-design-animation-tv"
to = "/project/bbc-entertainment"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/yankees-creative-design"
to = "/project/yankees"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/sermo-branding-design-web-development"
to = "/project/sermo"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/bbc-entertainment-mina-jack-animation-design-tv"
to = "/project/mina-and-jack"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/bbc-entertainment-HD-design-animation-tv"
to = "/project/bbc-hd"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/bbc-entertainment-cbeebies-creative"
to = "/project/cbeebies-bbc"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/le-cordon-bleu-creative-design-web-development"
to = "/project/le-cordon-bleu"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/onboard-informatics-design-web-development"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/the-long-way-back-entertainment-design-animation"
to = "/project/the-long-way-back"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/univision-election-design-animation-tv"
to = "/project/univision"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/sambazon-design-animation"
to = "/project/sambazon"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/steelbridge-labs-incubator-branding-web-design"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/simply-ira-iralogix-branding-design-web"
to = "/wok"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/global-press-design"
to = "/project/global-press"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/indago-design-animation"
to = "/project/indago"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/investigation-13-entertainment-design-animation"
to = "/project/investigation-13"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/fusion-beauty-creative-packaging"
to = "/project/fusion-beauty"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/quantgene-is-a-cell-free-platform"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/lufthansa-creative-design-web-development"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/repair-the-world"
to = "/project/repair-the-world"
status = 301
force = false

[[redirects]]
from = "/#/creative-work/clearvuze"
to = "/project/clearvuze"
status = 301
force = false

[[redirects]]
from = "/creative-work/allocate"
to = "/project/allocaterite"
status = 301
force = false

[[redirects]]
from = "/creative-work/awake"
to = "/project/awake"
status = 301
force = false

[[redirects]]
from = "/creative-work/smart-cities"
to = "/project/smartcities"
status = 301
force = false

[[redirects]]
from = "/creative-work/humanifed-branding-web-design-app-development"
to = "/project/humanified"
status = 301
force = false

[[redirects]]
from = "/creative-work/ultra-music-animation-design-web-development"
to = "/project/ultra"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-london-calling-design"
to = "/project/london-calling"
status = 301
force = false

[[redirects]]
from = "/creative-work/showtime"
to = "/project/ray-donovan"
status = 301
force = false

[[redirects]]
from = "/creative-work/base-develops-and-manages"
to = "/project/base"
status = 301
force = false

[[redirects]]
from = "/creative-work/coloredge-is-a-unique-media-company"
to = "/project/coloredge"
status = 301
force = false

[[redirects]]
from = "/creative-work/city-cancer-challenge"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/rock-summer-is-an-initiative-started"
to = "/project/rock-summer"
status = 301
force = false

[[redirects]]
from = "/creative-work/pluto-tv-is-an-Internet-based-television"
to = "/project/pluto-tv"
status = 301
force = false

[[redirects]]
from = "/creative-work/oracle-cloud-hero-marketing-design-web-development"
to = "/project/oracle"
status = 301
force = false

[[redirects]]
from = "/creative-work/hugo-boss-design-animation"
to = "/project/hugo-boss"
status = 301
force = false

[[redirects]]
from = "/creative-work/first-key-homes-strategy-design-web-development"
to = "/project/first-key-homes"
status = 301
force = false

[[redirects]]
from = "/creative-work/the-department-design-web-development"
to = "/project/the-department"
status = 301
force = false

[[redirects]]
from = "/creative-work/engine-shop-branding-design-web-development"
to = "/project/engineshop"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-design-animation-tv"
to = "/project/bbc-entertainment"
status = 301
force = false

[[redirects]]
from = "/creative-work/yankees-creative-design"
to = "/project/yankees"
status = 301
force = false

[[redirects]]
from = "/creative-work/sermo-branding-design-web-development"
to = "/project/sermo"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-mina-jack-animation-design-tv"
to = "/project/mina-and-jack"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-HD-design-animation-tv"
to = "/project/bbc-hd"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-cbeebies-creative"
to = "/project/cbeebies-bbc"
status = 301
force = false

[[redirects]]
from = "/creative-work/le-cordon-bleu-creative-design-web-development"
to = "/project/le-cordon-bleu"
status = 301
force = false

[[redirects]]
from = "/creative-work/onboard-informatics-design-web-development"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/the-long-way-back-entertainment-design-animation"
to = "/project/the-long-way-back"
status = 301
force = false

[[redirects]]
from = "/creative-work/univision-election-design-animation-tv"
to = "/project/univision"
status = 301
force = false

[[redirects]]
from = "/creative-work/sambazon-design-animation"
to = "/project/sambazon"
status = 301
force = false

[[redirects]]
from = "/creative-work/steelbridge-labs-incubator-branding-web-design"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/simply-ira-iralogix-branding-design-web"
to = "/wok"
status = 301
force = false

[[redirects]]
from = "/creative-work/global-press-design"
to = "/project/global-press"
status = 301
force = false

[[redirects]]
from = "/creative-work/indago-design-animation"
to = "/project/indago"
status = 301
force = false

[[redirects]]
from = "/creative-work/investigation-13-entertainment-design-animation"
to = "/project/investigation-13"
status = 301
force = false

[[redirects]]
from = "/creative-work/fusion-beauty-creative-packaging"
to = "/project/fusion-beauty"
status = 301
force = false

[[redirects]]
from = "/creative-work/quantgene-is-a-cell-free-platform"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/lufthansa-creative-design-web-development"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/repair-the-world"
to = "/project/repair-the-world"
status = 301
force = false

[[redirects]]
from = "/creative-work/clearvuze"
to = "/project/clearvuze-2"
status = 301
force = false

[[redirects]]
from = "/work/humanifed/"
to = "/project/humanified"
status = 301
force = false

[[redirects]]
from = "/work/humanified/"
to = "/project/humanified"
status = 301
force = false

[[redirects]]
from = "/creative-work/city-cancer-challenge.html"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/hugo-boss-design-animation.html"
to = "/project/hugo-boss"
status = 301
force = false

[[redirects]]
from = "/creative-work/onboard-informatics-design-web-development.html"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/portfolio/bbc-entertainment-2/"
to = "/project/london-calling"
status = 301
force = false

[[redirects]]
from = "/projects/fusion-beauty.html"
to = "/project/fusion-beauty"
status = 301
force = false

[[redirects]]
from = "/creative-work/repair-the-world"
to = "/project/repair-the-world"
status = 301
force = false

[[redirects]]
from = "/creative-work/yankees-creative-design.html"
to = "/project/yankees"
status = 301
force = false

[[redirects]]
from = "/creative-work/indago-design-animation.html"
to = "/project/indago"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-design-animation-tv.html"
to = "/project/bbc-hd"
status = 301
force = false

[[redirects]]
from = "/creative-work/investigation-13-entertainment-design-animation.html"
to = "/project/investigation-13"
status = 301
force = false

[[redirects]]
from = "/creative-work/steelbridge-labs-incubator-branding-web-design"
to = "/work"
status = 301
force = false

[[redirects]]
from = "/creative-work/engine-shop-branding-design-web-development.html"
to = "/project/engineshop"
status = 301
force = false

[[redirects]]
from = "/creative-work/humanifed-branding-web-design-app-development.html"
to = "/project/humanified"
status = 301
force = false

[[redirects]]
from = "/creative-work/bbc-entertainment-mina-jack-animation-design-tv.html"
to = "/project/mina-and-jack"
status = 301
force = false

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
